name: Deploy to AWS EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p ~/my-app
          cd ~/my-app
          
          if [ -d ".git" ]; then
            git pull origin master
          else
            git clone https://github.com/${{ github.repository }} .
          fi
          
          docker stop my-app-container 2>/dev/null || true
          docker rm my-app-container 2>/dev/null || true
          docker rmi my-app 2>/dev/null || true
          
          docker build -t my-app .
          docker run -d -p 80:3000 --name my-app-container --restart unless-stopped my-app
          
          docker image prune -f
